---
title: "Ch12"
author: "Chathrua Gunasekara"
date: "November 22, 2014"
output: word_document
---
1.a
```{r,echo=FALSE}
rm(list=ls())
library("caret")
library("AppliedPredictiveModeling")
data(hepatic)
barplot(table(injury))


#biological predictors

nzro <- nearZeroVar(bio)
length(nzro)
dim(bio[,-nzro])
filteredbio <- bio[,-nzro]
filteredbio <- filteredbio[,-findCorrelation(cor(filteredbio))]
comboInfo <- findLinearCombos(filteredbio)
comboInfo$remove
# No linear combinations
preProcValues <- preProcess(filteredbio, method = c("center", "scale"))
Transformedbio <- predict(preProcValues, filteredbio)
trainIndex <- createDataPartition(injury, p = .8,list = FALSE,times = 1)

trainX<-Transformedbio[trainIndex,]
trainY<-factor(injury[trainIndex])
testX<-Transformedbio[-trainIndex,]
testY<-factor(injury[-trainIndex])


#---------------------------Logistic Regression
#Severe vs other
newInjury <- ifelse(injury == "Severe", "yes", "no")
table(newInjury)
barplot(table(newInjury))
trainIndex <- createDataPartition(newInjury, p = .8,list = FALSE,times = 1)

trainX<-Transformedbio[trainIndex,]
trainY<-factor(newInjury[trainIndex])
testX<-Transformedbio[-trainIndex,]
testY<-factor(newInjury[-trainIndex])

ctrl <- trainControl(method = "LGOCV",summaryFunction = twoClassSummary,classProbs = TRUE,savePredictions = TRUE)
lrSevere <- train(trainX,y = trainY,method = "glm",metric = "ROC",trControl=ctrl)
lrSevere
confusionMatrix(data = lrSevere$pred$pred,reference = lrSevere$pred$obs,positive="yes")
Roc <- roc(response = lrSevere$pred$obs,predictor = lrSevere$pred$yes,levels = rev(levels(lrSevere$pred$obs)))
plot(Roc, legacy.axes = TRUE)

confusionMatrix(predict(lrSevere,testX),testY,positive="yes")

#mild vs other
newInjury <- ifelse(injury == "Mild", "yes", "no")
table(newInjury)
barplot(table(newInjury))
trainIndex <- createDataPartition(newInjury, p = .8,list = FALSE,times = 1)

trainX<-Transformedbio[trainIndex,]
trainY<-factor(newInjury[trainIndex])
testX<-Transformedbio[-trainIndex,]
testY<-factor(newInjury[-trainIndex])

ctrl <- trainControl(method = "LGOCV",summaryFunction = twoClassSummary,classProbs = TRUE,savePredictions = TRUE)
lrMild <- train(trainX,y = trainY,method = "glm",metric = "ROC",trControl=ctrl)
lrMild
confusionMatrix(data = lrMild$pred$pred,reference = lrMild$pred$obs,positive="yes")
Roc <- roc(response = lrMild$pred$obs,predictor = lrMild$pred$yes,levels = rev(levels(lrMild$pred$obs)))
plot(Roc, legacy.axes = TRUE)

confusionMatrix(predict(lrMild,testX),testY,positive="yes")

#none vs other
newInjury <- ifelse(injury == "None", "yes", "no")
table(newInjury)
barplot(table(newInjury))
trainIndex <- createDataPartition(newInjury, p = .8,list = FALSE,times = 1)

trainX<-Transformedbio[trainIndex,]
trainY<-factor(newInjury[trainIndex])
testX<-Transformedbio[-trainIndex,]
testY<-factor(newInjury[-trainIndex])

ctrl <- trainControl(method = "LGOCV",summaryFunction = twoClassSummary,classProbs = TRUE,savePredictions = TRUE)
lrNone <- train(trainX,y = trainY,method = "glm",metric = "ROC",trControl=ctrl)
lrNone
confusionMatrix(data = lrNone$pred$pred,reference = lrNone$pred$obs,positive="yes")
Roc <- roc(response = lrNone$pred$obs,predictor = lrNone$pred$yes,levels = rev(levels(lrNone$pred$obs)))
plot(Roc, legacy.axes = TRUE)

confusionMatrix(predict(lrNone,testX),testY,positive="yes")



#--------------------LDA

ldaModel<- train(x = trainX,y = trainY,method = "lda2",metric="Kappa")
ldaModel
predLda<-predict(ldaModel,testX)
confusionMatrix(data=predLda,reference = testY)

#------------------plsda
plsdaModel <- train(x=trainX,y=trainY,method="pls",tuneGrid=expand.grid(.ncomp=1:5))
plsdaModel
confusionMatrix(predict(plsdaModel,testX),testY)

plsImp <- varImp(plsdaModel,scale=FALSE)
#penalized
glmnGrid <- expand.grid(.alpha = c(0, .1),.lambda=seq(0.1,0.2,length=10))
glmnTuned <- train(trainX,y=trainY,method="glmnet",tuneGrid=glmnGrid)
confusionMatrix(predict(glmnTuned,testX),testY)
###NSC################
nscGrid <- data.frame(.threshold = 0:25)
set.seed(476)
nscTuned <- train(x = trainX,
                   y = trainY,method = "pam",
                   #preProc = c("center", "scale"),
                   tuneGrid = nscGrid)
                   #metric = "ROC",
                   #trControl = ctrl)
nscTuned
confusionMatrix(predict(nscTuned,testX),testY)
varImp(nscTuned,scale=FALSE)


############################chem################

rm(list=ls())
library(caret)
data(hepatic)

nzro <- nearZeroVar(chem)
length(nzro)
filteredChem <- chem[,-nzro]
filteredChem <- filteredChem[,-findCorrelation(cor(filteredChem))]
comboInfo <- findLinearCombos(filteredChem)
comboInfo$remove
filteredChem <- filteredChem[,-comboInfo$remove]
# No linear combinations
preProcValues <- preProcess(filteredChem, method = c("center", "scale"))
TransformedChem<- predict(preProcValues, filteredChem)
trainIndex <- createDataPartition(injury, p = .8,list = FALSE,times = 1)

trainX<-TransformedChem[trainIndex,]
trainY<-factor(injury[trainIndex])
testX<-TransformedChem[-trainIndex,]
testY<-factor(injury[-trainIndex])
#---------LDA------
ldaModel<- train(x = trainX,y = trainY,method = "lda2",metric="kappa")
ldaModel
predLda<-predict(ldaModel,testX)
confusionMatrix(data=predLda,reference = testY)

#--------plsda----
plsdaModel <- train(x=trainX,y=trainY,method="pls",tuneGrid=expand.grid(.ncomp=1:5))
plsdaModel
confusionMatrix(predict(plsdaModel,testX),testY)

plsImp <- varImp(plsdaModel,scale=FALSE)
plsImp

#------#penalized
glmnGrid <- expand.grid(.alpha = c(0, .1),.lambda=seq(0.1,0.2,length=10))
glmnTuned <- train(trainX,y=trainY,method="glmnet",tuneGrid=glmnGrid)
confusionMatrix(predict(glmnTuned,testX),testY)
###
nscGrid <- data.frame(.threshold = 0:25)
set.seed(476)
nscTuned <- train(x = trainX,
                   y = trainY,method = "pam",
                   tuneGrid = nscGrid)
nscTuned
confusionMatrix(predict(nscTuned,testX),testY)
varImp(nscTuned,scale=FALSE)

#------------------combination-----
rm(list=ls())
library(caret)
data(hepatic)
dataset <- cbind(bio,chem)

nzro <- nearZeroVar(dataset)
length(nzro)
filtereddataset <- dataset[,-nzro]
filtereddataset <- filtereddataset[,-findCorrelation(cor(filtereddataset))]
comboInfo <- findLinearCombos(filtereddataset)
comboInfo$remove
filtereddataset <- filtereddataset[,-comboInfo$remove]
# No linear combinations
preProcValues <- preProcess(filtereddataset, method = c("center", "scale"))
Transformed<- predict(preProcValues, filtereddataset)
trainIndex <- createDataPartition(injury, p = .8,list = FALSE,times = 1)

trainX<-Transformed[trainIndex,]
trainY<-factor(injury[trainIndex])
testX<-Transformed[-trainIndex,]
testY<-factor(injury[-trainIndex])

#------lda2---
ldaModel<- train(x = trainX,y = trainY,method = "lda2",metric="kappa")
ldaModel
predLda<-predict(ldaModel,testX)
confusionMatrix(data=predLda,reference = testY)

#--------plsda----
plsdaModel <- train(x=trainX,y=trainY,method="pls",tuneGrid=expand.grid(.ncomp=1:5))
plsdaModel
confusionMatrix(predict(plsdaModel,testX),testY)


#------#penalized
glmnGrid <- expand.grid(.alpha = c(0, .1),.lambda=seq(0.1,0.2,length=10))
glmnTuned <- train(trainX,y=trainY,method="glmnet",tuneGrid=glmnGrid)
confusionMatrix(predict(glmnTuned,testX),testY)


#------NSC
nscGrid <- data.frame(.threshold = 0:25)
set.seed(476)
nscTuned <- train(x = trainX,
                   y = trainY,method = "pam",
                   tuneGrid = nscGrid)
nscTuned
confusionMatrix(predict(nscTuned,testX),testY)
varImp(nscTuned,scale=FALSE)
```

2.a. Becuase the extream class imbalance the data set should be split using stratified sampling. 
```{r,echo=TRUE}
library(caret)
data(oil)
barplot(table(oilType))
library(corrplot)
corrplot(cor(fattyAcids), order = "hclust")
fattyAcids <- fattyAcids[,-findCorrelation(cor(fattyAcids))]

```
b. Because the class imbalance kappa statistic should be used.
c. Only LDA, PLSDA, NSC methods are used but logistic regression in not used beucase the number of classes is higher than 2.


```{r,echo=FALSE}
rm(list=ls())
library(caret)
data(oil)
library(corrplot)
corrplot(cor(fattyAcids), order = "hclust")
fattyAcids <- fattyAcids[,-findCorrelation(cor(fattyAcids))]
trainIndex <- createDataPartition(oilType, p = 0.75,list = FALSE,times = 1)
trainX <-fattyAcids[trainIndex,]
trainY <- as.factor(oilType[trainIndex])
testX<-fattyAcids[-trainIndex,]
testY <-as.factor(oilType[-trainIndex])

```
LDA
```{r,echo=FALSE}
ldaModel<- train(x =trainX ,y = trainY,method = "lda2",metric="Kappa",trControl = trainControl(method = "LOOCV"),preProcess = c("center", "scale"))
ldaModel
predLda<-predict(ldaModel,testX)
confusionMatrix(data=predLda,reference = testY)

```
PLSDA
```{r,echo=FALSE}
plsModel<- train(x = trainX,y = trainY,method = "pls",metric="Kappa",preProcess = c("center", "scale"))
plsModel
predpls<-predict(plsModel,testX)
confusionMatrix(data=predpls,reference = testY)
```
Penalized Models
```{r,echo=FALSE}
glmnGrid <- expand.grid(.alpha = c(0, .1, .2, .4, .6, .8, 1),.lambda=seq(0.01,0.2,length=40))
lmnTuned <- train(trainX,y = trainY,method = "glmnet",tuneGrid = glmnGrid,metric = "Kappa",preProcess = c("center", "scale"))
lmnTuned
predlmn<-predict(lmnTuned,testX)
confusionMatrix(data=predlmn,reference = testY)
```
NSC
```{r,echo=FALSE}
library(pamr)
nscGrid <- data.frame(.threshold = 0:25)
nscTuned <- train(x = trainX,
                  y = trainY,
                  method = "pam",
                  tuneGrid = nscGrid,preProcess = c("center", "scale"),
                  metric = "kappa")

nscTuned

prednsc<-predict(nscTuned,testX)
confusionMatrix(data=prednsc,reference = testY)
```



3.
```{r,echo=FALSE}
library(C50)
library(caret)
library(corrplot)
data(churn)
```

a.
```{r,echo=TRUE}
dataset <-rbind(churnTrain,churnTest)
# Remove Area code and state
dataset<-dataset[,-c(1,3)]
#create 1 | 0 for yes | no
dataset[,2] <- as.factor(ifelse(dataset[,2]=="yes","1","0"))
dataset[,3] <- as.factor(ifelse(dataset[,3]=="yes","1","0"))
dataset[,18] <- as.factor(ifelse(dataset[,18]=="yes","1","0"))

X <- dataset[,-18]

#Check near Zero variance predictores
nzro <- nearZeroVar(X)
nzro
X <-X[,-nzro]
corrplot(cor(X[,-c(2,3)]),method="color")
numerics <- X[,-c(2,3)]
library(corrplot)
M <- cor(numerics)
corrplot(M, method = "color")
numerics <- numerics[,-findCorrelation(cor(numerics))]
#Removing high correlated predictors
Y <-dataset[,18]
barplot(table(Y))

trainIndex <- createDataPartition(Y, p = .75,list = FALSE,times = 1)
trainX <-numerics[trainIndex,]
trainY <-Y[trainIndex]
testX <- numerics[-trainIndex,]
testY <- Y[-trainIndex]

```

b.

```{r,echo=FALSE}
ctrl <- trainControl(method = "LGOCV",
                     summaryFunction = twoClassSummary,
                     classProbs = TRUE,
                     savePredictions = TRUE)

library(caret)
set.seed(476)
glmModel <- train(trainX,y = trainY,method = "glm",metric = "ROC",trControl = ctrl,preProc = c("center", "scale"))
glmModel

glmPred <- predict(glmModel,testX)
confusionMatrix(data=glmPred,reference = testY)

```
```{r,echo=FALSE}
ldaModel<- train(x = trainX,y = trainY,method = "lda",metric = "ROC",trControl = ctrl,preProc = c("center", "scale"))
ldaModel
ldaPred <- predict(ldaModel,testX)
confusionMatrix(data=ldaPred,reference = testY)
```

```{r,echo=FALSE}
plsdaModel <- train(x = trainX,y = trainY,
                                     method = "pls",
                                     tuneGrid = expand.grid(.ncomp = 1:2),
                                     preProc = c("center","scale"),
                                     metric = "ROC",
                                     trControl = ctrl)
plsdaPred <- predict(plsdaModel,testX)
confusionMatrix(data=plsdaPred,reference = testY)
```

```{r,echo=FALSE}
glmnGrid <- expand.grid(.alpha = c(0, .1, .2, .4, .6, .8, 1),.lambda=seq(0.01,0.2,length=40))
lmnTuned <- train(trainX,y = trainY,method = "glmnet",  tuneGrid = glmnGrid,metric = "ROC",trControl = ctrl,preProc = c("center", "scale"))
lmnTuned
lmnPred <- predict(lmnTuned,testX)
confusionMatrix(data=lmnPred,reference = testY)
```

```{r,echo=FALSE}
library(pamr)
nscGrid <- data.frame(.threshold = 0:25)
nscTuned <- train(x = trainX,
                                       y = trainY,
                                       method = "pam",
                                       preProc = c("center", "scale"),
                                       tuneGrid = nscGrid,
                                       metric = "ROC",
                                       trControl = ctrl)


nscTuned
nscPred <- predict(nscTuned,testX)
confusionMatrix(data=nscPred,reference = testY)

```





