---
title: "Qualifying Exam"
author: "Chathrua Gunasekara"
date: "December 22, 2014"
output: word_document
---
1) 
a. Using the poisson distribution, p(X=0) given lambda = 3.2
```{r,echo=TRUE}
dpois(0,3.2)
```
b.Expected Value = lambda x 1 = 3.2 
variance = lambda  = 3.2

2.
```{r, echo=TRUE}
#a)
#P(yi<=2)=p(y=0)+p(y=1)+p(y=2)
0.005+0.010+0.035
#b)
#P(yi>0)=p(y=1)+p(y=2)+p(y=3)+p(y=4)
0.010+0.035+0.050+0.09
#c)mu = sigma(x.P(x))
mu<-0*0.005+1*0.01+2*0.035+3*0.050+4*0.9

#d)
temp <-(0^2)*0.005+(1^2)*0.010+(2^2)*0.035+(3^2)*0.050+(4^2)*0.9
var <-sqrt(temp-mu^2)
var
sd <-var^2
sd
```
3.
```{r,echo=TRUE}
mu = 70
sigma = 3
#64
(64-70)/3
(76-70)/3
#between -2 and +2
pnorm(2) - pnorm(-2)

```
4.
```{r,echo=TRUE}
#a)Sample mean
values <-c(13.3,14.5,15.3,15.3,14.3,14.8,15.2,14.9,14.6,14.1)
mean(values)

#b)sample variance
var(values)
#sample standard deviation
sqrt(var(values))

#c)
xbar <- 14.63          # sample mean 
mu0 <- 14.90           # hypothesized value 
s <- sqrt(0.389)               # sample standard deviation 
n <- 10              # sample size 

test_statistic <- (xbar-mu0)/(s/sqrt(n))
test_statistic

alpha = .01
df <- n-1
t.half.alpha <- qt(1-alpha/2,df=n-1)
c(-t.half.alpha,t.half.alpha)

pval <- 2*pt(test_statistic,df=n-1)
pval

#http://www.r-tutor.com/elementary-statistics/hypothesis-testing/two-tailed-test-population-mean-unknown-variance


e <-qt(0.9,df=n-1)*s
e
c(xbar-e,xbar+e)

#true mean is between this confidence interval so it has not been changed.

```

5)
1. c

2. b

3. c

4. c

5. a




